//-*- coding: utf-8-unix -*-
plugins {
    id 'java'
    id 'io.quarkus'
}

apply from: "$rootProject.projectDir/versions.gradle"

allprojects {
    group = 'se.laz.casual'
    version = '1.0.0-SNAPSHOT'

    repositories {
        mavenCentral()
        maven {
            name = 'Central Portal Snapshots'
            url = 'https://central.sonatype.com/repository/maven-snapshots/'
            content {
                includeGroup("se.laz.casual")
            }
        }
        mavenLocal()
    }
    tasks.withType(GenerateModuleMetadata).configureEach {
        suppressedValidationErrors.add('enforced-platform')
    }
}


dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-rest'
    // you should run ../gradlew clean build publishToMavenLocal first
    implementation libs.casual_quarkus
    implementation libs.commons_io

    runtimeOnly libs.gson

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
}
