//-*- coding: utf-8-unix -*-
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
    plugins {
        id "${quarkusPluginId}" version "${quarkusPluginVersion}"
        id 'io.quarkus.extension' version "${quarkusPluginVersion}"
}
}
rootProject.name='casual-quarkus'

include 'runtime'
include 'deployment'

project(':runtime').name = 'casual-quarkus'
project(':deployment').name = 'casual-quarkus-deployment'

