//-*- coding: utf-8-unix -*-
plugins {
    id 'java-library'
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation "io.quarkus:quarkus-core-deployment:${quarkusPlatformVersion}"
    implementation libs.ironjacamar_deployment
    implementation "io.quarkus:quarkus-narayana-jta-deployment:${quarkusPlatformVersion}"
    implementation "io.quarkus:quarkus-scheduler-deployment:${quarkusPlatformVersion}"
    implementation project(':casual-quarkus')

    annotationProcessor "io.quarkus:quarkus-extension-processor:${quarkusPlatformVersion}"
}

// See runtime/build.gradle for explanation
tasks.register('generateExtensionPom') {
    def pomFile = layout.buildDirectory.file('classes/pom.xml')
    outputs.file(pomFile)
    doLast {
        pomFile.get().asFile.text = """\
<?xml version="1.0" encoding="UTF-8"?>
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>${project.group}</groupId>
    <artifactId>${project.name}</artifactId>
    <version>${project.version}</version>
</project>
"""
    }
}
tasks.named('compileJava') {
    dependsOn 'generateExtensionPom'
}


