#-*- coding: utf-8-unix -*-
# NOTE:
# At least one pool HAS to be named casual!
quarkus.ironjacamar.casual.ra.kind=casual
quarkus.ironjacamar.casual.ra.config.host=10.105.139.20
quarkus.ironjacamar.casual.ra.config.port=7771
quarkus.ironjacamar.casual.ra.config.network-connection-pool-size=1
quarkus.ironjacamar.casual.ra.config.network-connection-pool-name=casual-pool
quarkus.ironjacamar.casual.ra.config.inbound-server-port=7772

# another pool - can be named anything but casual
quarkus.ironjacamar.casual-two.ra.kind=casual
quarkus.ironjacamar.casual-two.ra.config.host=10.106.212.24
quarkus.ironjacamar.casual-two.ra.config.port=7771
quarkus.ironjacamar.casual-two.ra.config.network-connection-pool-size=1
quarkus.ironjacamar.casual-two.ra.config.network-connection-pool-name=casual-two-pool

# if you want to fat jar your application
quarkus.package.jar.type=uber-jar

# we do not want calls to block a whole thread
quarkus.virtual-threads.enabled=true
