#-*- coding: utf-8-unix -*-
# NOTE:
# At least one pool HAS to be named casual!
quarkus.ironjacamar.casual.ra.kind=casual
quarkus.ironjacamar.casual.ra.config.host=localhost
quarkus.ironjacamar.casual.ra.config.port=7771
quarkus.ironjacamar.casual.ra.config.network-connection-pool-size=1
quarkus.ironjacamar.casual.ra.config.network-connection-pool-name=casual-pool
quarkus.ironjacamar.casual.ra.config.inbound-server-port=7772

# overrides for other profile
%peer.quarkus.http.port=8000
$peer.quarkus.debug.port=5006
%peer.quarkus.ironjacamar.casual.ra.config.port=7772
%peer.quarkus.ironjacamar.casual.ra.config.inbound-server-port=7771

# another pool - can be named anything but casual
#quarkus.ironjacamar.casual-two.ra.kind=casual
#quarkus.ironjacamar.casual-two.ra.config.host=somehost
#quarkus.ironjacamar.casual-two.ra.config.port=someport
#quarkus.ironjacamar.casual-two.ra.config.network-connection-pool-size=1
#quarkus.ironjacamar.casual-two.ra.config.network-connection-pool-name=casual-pool-two

# if you want to fat jar your application
quarkus.package.jar.type=uber-jar

# we do not want calls to block a whole thread - very important for throughput
quarkus.virtual-threads.enabled=true

# netty
#quarkus.jvm.args=-Dio.netty.tryReflectionSetAccessible=true

# for soak testing
quarkus.ironjacamar.casual.ra.cm.pool.config.min-size=5000
quarkus.ironjacamar.casual.ra.cm.pool.config.max-size=5000
quarkus.ironjacamar.casual.ra.cm.pool.config.initial-size=5000

quarkus.thread-pool.max-threads=200

# logging
#quarkus.log.category."io.netty".level=TRACE
#quarkus.log.category."io.netty".min-level=TRACE

#quarkus.log.category."se.laz.casual".level=TRACE
#quarkus.log.category."se.laz.casual".min-level=TRACE

# Also raise the global minimum level so TRACE messages are not filtered out at build time
#quarkus.log.min-level=TRACE

# Optional: Raise the console handler level as well (recommended in dev mode)
#quarkus.log.console.level=TRACE
